"""
StyleTTS2 reproduction validation utilities.

This script checks whether a training checkpoint generated by the
reproduction pipeline can be found and loaded successfully.
"""

import argparse
from pathlib import Path

import torch


def validate_checkpoint(checkpoint_path: str):
    checkpoint = Path(checkpoint_path)

    print("=== StyleTTS2 Checkpoint Validation ===")
    print(f"Checkpoint: {checkpoint}")

    if not checkpoint.exists():
        raise FileNotFoundError(
            f"Checkpoint does not exist: {checkpoint}"
        )

    size_mb = checkpoint.stat().st_size / (1024 ** 2)

    print(f"Checkpoint size: {size_mb:.2f} MB")
    print("Loading checkpoint...")

    state = torch.load(
        checkpoint,
        map_location="cpu",
        weights_only=False,
    )

    print("[OK] Checkpoint loaded successfully")

    if isinstance(state, dict):
        print("\nTop-level checkpoint keys:")
        for key in state.keys():
            print(f"  - {key}")

        if "epoch" in state:
            print(f"\nEpoch: {state['epoch']}")

        if "iters" in state:
            print(f"Iterations: {state['iters']}")

    print("\n=== VALIDATION OK ===")


def main():
    parser = argparse.ArgumentParser(
        description="Validate a StyleTTS2 training checkpoint."
    )

    parser.add_argument(
        "--checkpoint",
        type=str,
        default="Models/LJSpeech_smoke/first_stage.pth",
        help="Path to the checkpoint to validate.",
    )

    args = parser.parse_args()

    validate_checkpoint(args.checkpoint)


if __name__ == "__main__":
    main()
